python train.py \
--output_dir ./models/train_dataset \
--do_train \
--do_eval \
--model_name_or_path "klue/roberta-large" \
--overwrite_output_dir True \
--per_device_train_batch_size 32 \
--per_device_eval_batch_size 32 \
--learning_rate 3e-5 \
--num_train_epochs 3 \
--weight_decay 0.01 \
--warmup_ratio 0.1 \
--logging_steps 100 \
--evaluation_strategy "steps" \
--eval_steps 100 \
--save_strategy "steps" \
--fp16 True \
--load_best_model_at_end True \
--wandb_project_name "mrc_test" \
--wandb_entity "salmons" \
--wandb_run_name "baseline"